networks:
  todo-network:
    driver: bridge

volumes:
  postgres-data:

services:
  todo-backend:
    image: todo-backend:latest
    container_name: todo-backend
    env_file: ./.env
    depends_on:
      todo-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - todo-network
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}

  todo-db:
    image: postgres:latest
    container_name: todo-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-network
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_DATABASE}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 15s
    ports:
      - ${DB_PORT}:${DB_PORT}
